#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: harbor.ntppool.org/ntppool/monitor-api
  # -- image tag, defaults to appVersion
  #tag: 
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [monitor-api documentation](https://go.ntppool.org/monitor/cmd/monitor-api).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

podLabels:
  tier: frontend

command:
  - /app/monitor-api

args:
  - server


# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    annotations:
      #haproxy-ingress.github.io/secure-backends: "true"
      haproxy-ingress.github.io/health-check-uri: "/__health"
      haproxy-ingress.github.io/health-check-port: "8080"
      
    ports:
      http:
        port: 443
        targetPort: 8000
        protocol: TCP

      health:
        enabled: true
        port: 8080
        protocol: HTTP


ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  {}
  # data:
  #   enabled: false
  #   mountPath: /data

probes:
  liveness:
    custom: true
    spec:
      failureThreshold: 2
      httpGet:
        path: /__health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 4
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 1
  readiness:
    custom: true
    spec:
      failureThreshold: 2
      httpGet:
        path: /__health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 4
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 1
