{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "splash.serviceAccountName" . }}
  labels:
{{ include "splash.labels" . | nindent 4 }}
{{- end -}}
