apiVersion: v1
data:
  {{- toYaml .Values.config | nindent 2 }}
kind: ConfigMap
metadata:
  name: {{ include "ntppool.fullname" . }}-config
  annotations:
  labels:
    {{- include "ntppool.chartLabels" . | nindent 4 }}
