{{ if .Values.ingress.enabled -}}

{{ $g := . }}
{{ $values := $g.Values }}
{{ $config := .Values.config }}

{{ $fullName := include "ntppool.fullname" . -}}

{{ range $ingress_type := .Values.ingress.types }}
---
{{ $svcPort := $values.service.port -}}
apiVersion: networking.k8s.io/v1
{{ $hosts := "" }}
{{ if eq $ingress_type "manage" }}
{{   $hosts = splitList "," $config.manage_hostname }}
{{ else }}
{{   $hosts = splitList "," $config.web_hostname }}
{{ end }}
{{ $tls := false }}
{{ if eq $ingress_type "manage" }}
{{   $tls = eq $config.manage_tls "yes" }}
{{ else }}
{{   $tls = eq $config.web_tls "yes" }}
{{ end }}

kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $ingress_type }}
  labels:
    {{ include "ntppool.labels" $g | nindent 4 }}
  annotations:
  {{- if $values.ingress.class }}
    # this might be needed on older kubernetes installs, but
    # we can't set both this and the ingressClassName anymore it seems.
    # kubernetes.io/ingress.class: {{ $values.ingress.class }}
  {{- end }}
  {{- if $tls }}
    kubernetes.io/tls-acme: "true"
  {{ end }}

  {{ with $values.ingress.annotations }}
    {{ toYaml . | nindent 4 }}
  {{ end }}
spec:
{{- if $values.ingress.class }}
  ingressClassName: {{ $values.ingress.class }}
{{- end }}
{{ if $tls }}
  tls:
    - hosts:
      {{ range $hosts }}
        - {{ . | quote }}
      {{ end }}
      secretName: {{ $fullName }}-{{ $ingress_type }}-tls
{{ end }}
  rules:
  {{ range $hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
  {{ end }}
{{ end }}
{{ end }}