{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ntppool.serviceAccountName" . }}
  labels:
{{ include "ntppool.labels" . | nindent 4 }}
{{- end -}}
