apiVersion: v1
kind: Service
metadata:
  name: {{ include "ntppool.fullname" . }}
  labels:
    {{- include "ntppool.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8299
      protocol: TCP
      name: http
  selector:
    {{- include "ntppool.selectorLabels" . | nindent 4 }}
    tier: frontend
