apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dnsdist.fullname" . }}-config
  annotations:
  labels:
    {{- include "dnsdist.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}
