apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geoip.fullname" . }}
  labels:
    {{- include "geoip.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "geoip.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "geoip.selectorLabels" . | nindent 8 }}
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "geoip.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8009
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: geodns-data
            subPath: geoip
            mountPath: /usr/share/GeoIP/

        - name: geoip
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: maxmindinc/geoipupdate:v4.8.0
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          {{- with .Values.geoipupdate.config_script }}
          command: ["sh", "-c", "source {{ . }} && /usr/bin/entry.sh"]
          {{- end }}

          env:
          {{- with .Values.geoipupdate.account_id }}
          - name:  GEOIPUPDATE_ACCOUNT_ID
            value: "{{ . }}"
          {{- end }}
          {{- with .Values.geoipupdate.license_key }}
          - name:  GEOIPUPDATE_LICENSE_KEY
            value: "{{ . }}"
          {{- end }}
          - name:  GEOIPUPDATE_FREQUENCY
            value: "16"
          - name:  GEOIPUPDATE_PRESERVE_FILE_TIMES
            value: "1"
          - name:  GEOIPUPDATE_CONF_FILE
            value: "/tmp/geoip.conf"
          - name:  GEOIPUPDATE_EDITION_IDS
            value: "GeoLite2-City GeoLite2-Country GeoLite2-ASN"
          - name:  GEOIPUPDATE_VERBOSE
            value: "0"

          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 500m
              memory: 200Mi
          volumeMounts:
          - name: geodns-data
            subPath: geoip
            mountPath: /usr/share/GeoIP/
          - name: tmp
            mountPath: /tmp/

      volumes:
      - name: geodns-data
        emptyDir: {}
      - name: tmp
        emptyDir: {}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
