{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "geoip.serviceAccountName" . }}
  labels:
{{ include "geoip.labels" . | nindent 4 }}
{{- end -}}
